job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    tools {
        maven 'LocalMaven'
    }
    scm {
        git("https://github.com/anshulc55/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('H/5 * * * *')
    }
    steps {
        maven('package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
